### ISSUE TITLE
preg_match(): Compilation failed: two named subpatterns have the same name

### ISSUE THREAD

**Issue by aolko** [DeveloperMarius/simple-php-router#12]
```
SimpleRouter::group(['prefix' => '/orders'], function () {
    SimpleRouter::get('/', function ()    {
        echo 'Orders';
    });
    SimpleRouter::get('/inProgress', function ()    {
        echo 'In progress';
    });
    SimpleRouter::get('/done', function ()    {
        echo 'Done';
    });
});
SimpleRouter::group(['prefix' => '/clients'], function () {
    SimpleRouter::get('/', function ()    {
        echo 'Clients';
    });
    SimpleRouter::get('/client/{id}', function ($clientId)    {
        echo "Client #{$clientId}";
    });
});
SimpleRouter::group(['prefix' => '/order'], function () {
    SimpleRouter::get('/{id}', function ($orderId)    {
        echo "Order #{$orderId}";
    });
    SimpleRouter::group(['prefix' => '/edits'], function () {
        SimpleRouter::get('/', function ()    {
            echo 'Edits';
        });
    });
    SimpleRouter::get('/edit/{datetime}', function ($editDatetime)    {
        echo "Edit from#{$editDatetime}";
    });
    SimpleRouter::group(['prefix' => '/incidents'], function () {
        SimpleRouter::get('/', function ()    {
            echo 'Incidents';
        });
    });
    SimpleRouter::get('/incident/{id}', function ($incidentId)    {
        echo "Incident #{$incidentId}";
    });
});
```
While having my routes i'm getting an output __and__ this warning:
```
Warning: preg_match(): Compilation failed: two named subpatterns have the same name (PCRE2_DUPNAMES not set) at offset 54 in E:\OSPanel540\domains\card-tracker.local\vendor\developermarius\simple-router\src\Pecee\SimpleRouter\Route\Route.php on line 165
```
Also, why having params in the group prefix leads to errors?

**Comment by DeveloperMarius** [comment]
Hello,

I cannot reproduce this warning. Can you provide more information like the php version, router version and which example request you are using?

~ Marius

**Comment by aolko** [comment]
php 8.1, 
```
"developermarius/simple-router": "5.1.0.6"
```
[Routes](https://paste.ee/p/Tk9Wu#gjnZFb3kay2fwDITvJn0YiPDDMRA6805).

It mainly stumbles with `<word>`/`<word>s`.

**Comment by aolko** [comment]
still can't reproduce a week later?

**Comment by DeveloperMarius** [comment]
Hello,
I still cannot reproduce the warning in php 8.1.3
I am using your routes and I tested the route `/order/edits`.
In my tests the request is matching two routes, because `edits` is also understood as an `id`.
To fix this you have to define that the id is for example an integer using a RegEx:
```
TestRouter::get('/{id}', function ($orderId) {
     echo "Order #{$orderId}";
})->where(array('id' => '\d+'));
```

Feel free to provide more information or create a PR with a fix.

~ Marius

**Comment by aolko** [comment]
and in such cases [klein's simplified variables with types](https://github.com/klein/klein.php#:~:text=%5B%20match_type%20%3A%20param_name%20%5D) would be nice

**Comment by aolko** [comment]
will you implement that? @DeveloperMarius

**Comment by DeveloperMarius** [comment]
Hello,

I currently do not have the time to develop this feature request, but I added it to my list.
I will take a look at it when I have time. Until then feel free to use the `->where()` method as described.

Feel also free to create a PR. Nice idea though^^

~ Marius

**Comment by aolko** [comment]
if this is completed, can you share a snippet?
