### ISSUE TITLE
Dependabot and Renovate do not recognize it as a dependency

### ISSUE THREAD

**Issue by riku22** [DeveloperMarius/simple-php-router#14]
Hello.

I'm not sure if this is the right place to ask this question, but if you do, please let me know.

I used Dependabot to try to keep up with version upgrades of this library.
However, Dependabot didn't seem to recognize it as a dependency and didn't create an upgrade pull request.
Therefore, I switched to the method using Renovate, but it seems that this method is not recognized as a dependency too.

Ref: [riku22/simple-router-renovate/issues/3](https://github.com/riku22/simple-router-renovate/issues/3)

I don't think there is anything wrong with this setting, but is there anything that comes to mind?

PS: I think it's probably because the version number format is something like "5.1.0.17".
Composer seems to recommend a format like "5.1.17".

**Comment by DeveloperMarius** [comment]
Hey,

I will try to use the different version format.

~ Marius

**Comment by riku22** [comment]
Thank you.

I've only checked with Rnovate, but I think it's probably resolved.

Sincerely.
