### ISSUE TITLE
Get parameter

### ISSUE THREAD

**Issue by AlexJMcloud** [DeveloperMarius/simple-php-router#16]
How can I get a GET parameter without declaring it in a method.
Route:
static::get('/{lang}/about', 'Page@index');

I want to define it in the constructor since it is used throughout the site. But without an explicit declaration in the url - '/lang/{lang}/about'.

Or should I parse the query string myself?

**Comment by AlexJMcloud** [comment]
And one more thing, when specifying the route '/{lang}/' and '/admin/' - the router selects the first match. Route '/admin/' - it completely ignores. How can I fix this behavior?

**Comment by AlexJMcloud** [comment]
Or should I stop using routers from Github altogether and use Apache?

**Comment by DeveloperMarius** [comment]
> And one more thing, when specifying the route '/{lang}/' and '/admin/' - the router selects the first match. Route '/admin/' - it completely ignores. How can I fix this behavior?

You can use a regex to distinct language short codes form admin. 
For example: `static::get('/{lang}/about', 'Page@index')->where(['lang' => 'de|en']);`

**Comment by DeveloperMarius** [comment]
> How can I get a GET parameter without declaring it in a method. Route: static::get('/{lang}/about', 'Page@index');
> 
> I want to define it in the constructor since it is used throughout the site. But without an explicit declaration in the url - '/lang/{lang}/about'.
> 
> Or should I parse the query string myself?

Can you repeat your question? I cannot follow you :D

~ Marius

**Comment by AlexJMcloud** [comment]
I abandoned your implementation in favor of my router. Thank you for your attention.
