### ISSUE TITLE
CSRF-Verifier - $include must not be accessed before initialization

### ISSUE THREAD

**Issue by xJuvi** [DeveloperMarius/simple-php-router#17]
Hello there,
as mentioned in the readme, I have extended the CSRFVerifier to exclude the public API paths. Thos worked.

```php
protected ?array $except = ['/api/v1/external/*',];
```

Now i extend the excepted paths to this:

```php
protected ?array $except = ['/api/v1/external/*', '/v1/aws/*'];
```

After deploy this change i catch the following exception:
```
<error>
	<dateline>1727001601</dateline>
	<script>vendor/developermarius/simple-router/src/Pecee/Http/Middleware/BaseCsrfVerifier.php</script>
	<line>63</line>
	<type>47</type>
	<friendly_type>Uncaught Exception</friendly_type>
	<message>Typed property MWE\Router\Middlewares\CsrfVerifier::$include must not be accessed before initialization</message>
	<back_trace>#0  Pecee\Http\Middleware\BaseCsrfVerifier->skip() called at [/vendor/developermarius/simple-router/src/Pecee/Http/Middleware/BaseCsrfVerifier.php:95]
#1  Pecee\Http\Middleware\BaseCsrfVerifier->handle() called at [/vendor/developermarius/simple-router/src/Pecee/SimpleRouter/Router.php:350]
#2  Pecee\SimpleRouter\Router->start() called at [/vendor/developermarius/simple-router/src/Pecee/SimpleRouter/SimpleRouter.php:74]
#3  Pecee\SimpleRouter\SimpleRouter::start() called at [/inc/Router/Router.php:42]
#4  MWE\Router\Router::start() called at [/index.php:44]
</back_trace>
</error>
```

After take a look into the BaseCsrfVerifier.php i saw, this variable is not defined but used. My try to solve the problem was adding the variable $include into my extended class. But it doesn't take effect. So to solve the error i defined this variable as empty array. After that the error is gone and everything is working again:

```php
<?php
namespace MWE\Router\Middlewares;

use Pecee\Http\Middleware\BaseCsrfVerifier;

class CsrfVerifier extends BaseCsrfVerifier
{
	protected ?array $except = ['/api/v1/external/*', '/v1/aws/*'];
	protected ?array $include = [];
}
```

Maybe it's a bad solution but it works. Can you check the issue and solve it?

**Comment by DeveloperMarius** [comment]
Hey,
thanks for reporting this issue.
I released a dev-master version of this repo that should fix your issue. Thus, it sould allow yoou to remove the `include` line.
Please let me know if this works for you. I will release a version when your other issue is closed.

~ Marius

**Comment by xJuvi** [comment]
Well done. It works with your fix.
