### ISSUE TITLE
Composer package?

### ISSUE THREAD

**Issue by aolko** [DeveloperMarius/simple-php-router#5]
Please provide a composer package

**Comment by DeveloperMarius** [comment]
Hey,

this is not so easy as it sounds. I want to keep the `\Pecee\...` namespace to be campatible with the main project and be backwards compatible. But when I want to submit the project under `DeveloperMarius/simple-php-router` packagist gives me two warnings:
- A package with the name [pecee/simple-router](https://packagist.org/packages/pecee/simple-router) already exists.
- The vendor name "pecee" was already claimed by someone else on Packagist.org. You may ask them to add your package and give you maintainership access. If they add you as a maintainer on any package in that vendor namespace, you will then be able to add new packages in that namespace. The packages already in that vendor namespace can be found at [pecee](https://packagist.org/packages/pecee/).If those packages belong to you but were submitted by someone else, you can [contact us](mailto:contact@packagist.org) to resolve the issue.

It seems that packagist is not allowing me to publish a repo with `\Pecee\...`. I'm in contact with the support. Until then you can use the VCS repository.

~ Marius

**Comment by aolko** [comment]
yeeeah, i had to jump through hoops to obtain a github token to add the repo, oh and your readme.md snippet is invalid, here's the valid one:
```
{
  "repositories": [
      {
        "type": "vcs",
        "url": "https://github.com/developermarius/simple-php-router"
      },
      {
        "type": "composer",
        "url": "https://packagist.org"
      }
  ],
  "require": {
      "php": ">=8.0",
      "pecee/simple-router": "^5"
  }
}
```

**Comment by DeveloperMarius** [comment]
Hey,
I hope to get it working soon. 
I will change the snippet.

~ Marius

**Comment by DeveloperMarius** [comment]
Hey,
the composer package is out:
```
composer require developermarius/simple-router
```

~ Marius
