### ISSUE TITLE
Groups

### ISSUE THREAD

**Issue by aolko** [DeveloperMarius/simple-php-router#6]
Can i use the groups the same way as in [klein.php](https://github.com/klein/klein.php#route-namespaces)?
i.e. with plain, non-array, declaration

**Comment by DeveloperMarius** [comment]
Hello,

very interesting approach.
I would be interested in a function like

```php
SimpleRouter::loadRoutes(ArticleController::class);
````
SampleController.class:
```php
class ArticleController{

use RouterUtils;

#[Route(Route::POST, '/')]
public function createArticle(){
   ...
}

#[Route(Route::GET, '/{id}')]
public function getArticle(#[ValidatorAttribute] int $id){
   ...
}

}
````

What do do think? Can you explain your wish a bit more?

~ Marius

**Comment by aolko** [comment]
> Hello,
> 
> very interesting approach. I would be interested in a function like
> 
> ```
> SimpleRouter::loadRoutes(ArticleController::class);
> ```
> 
> SampleController.class:
> 
> ```
> class ArticleController{
> 
> use RouterUtils;
> 
> #[Route(Route::POST, '/')]
> public function createArticle(){
>    ...
> }
> 
> #[Route(Route::GET, '/{id}')]
> public function getArticle(#[ValidatorAttribute] int $id){
>    ...
> }
> 
> }
> ```
> 
> What do do think? Can you explain your wish a bit more?
> 
> ~ Marius

i think i just want a drop-in klein.php replacement with the __same or extended__ features without OO bs like MVC and middlewares

**Comment by DeveloperMarius** [comment]
We also have [Groups](https://github.com/DeveloperMarius/simple-php-router#router-groups) or [partial groups](https://github.com/DeveloperMarius/simple-php-router#partial-groups). 
You don't have to use MVC or middlewares. You can just [pass a function](https://github.com/DeveloperMarius/simple-php-router#router-groups) instead of the controller.
You can read more in the docs.

~ Marius

**Comment by aolko** [comment]
> We also have [Groups](https://github.com/DeveloperMarius/simple-php-router#router-groups) or [partial groups](https://github.com/DeveloperMarius/simple-php-router#partial-groups). You don't have to use MVC or middlewares. You can just [pass a function](https://github.com/DeveloperMarius/simple-php-router#router-groups) instead of the controller. You can read more in the docs.
> 
> ~ Marius

i know, i read the docs, but [because](https://github.com/DeveloperMarius/simple-php-router#:~:text=%5B%27middleware%27%20%3D%3E%20%5CDemo%5CMiddleware%5CAuth%3A%3Aclass%5D) [of](https://github.com/DeveloperMarius/simple-php-router#:~:text=%5B%27namespace%27%20%3D%3E%20%27Admin%27%5D) [this](https://github.com/DeveloperMarius/simple-php-router#partial-groups) i've made this issue in the first place

> You don't have to use MVC or middlewares.

I prefer to not being able to use them at all

**Comment by DeveloperMarius** [comment]
So you want a lightwise version of the router in a separate repo?
I mean you can just use the router in a simple way:

Add the .htaccess and an index.php:
```php
use Pecee\SimpleRouter\SimpleRouter;

require '../vendor/autoload.php';

SimpleRouter::get('/', function() {
    return 'Hello world';
});
SimpleRouter::post('/api/test', function() {
    SimpleRouter::response()->json(array(
        'success' => true
    ));
});

SimpleRouter::start();
```

It is a better practice to use MVC, middlewares etc, but like I said you can use the lightwise above version.

~ Marius

**Comment by aolko** [comment]
> ```
> use Pecee\SimpleRouter\SimpleRouter;
> 
> require '../vendor/autoload.php';
> 
> SimpleRouter::get('/', function() {
>     return 'Hello world';
> });
> SimpleRouter::post('/api/test', function() {
>     SimpleRouter::response()->json(array(
>         'success' => true
>     ));
> });
> 
> SimpleRouter::start();

your thinking is not broad enough, you are not accounting for __route groups__ like CRUD ones:
```
/api/v1/user/view
/api/v1/user/edit
/api/v1/user/delete
```
you absolutely **don't** want to copy-paste single get/post routes, you **want** them grouped

> So you want a lightwise version of the router in a separate repo?

**exactly the same or extended**, syntax/parity-wise

**Comment by DeveloperMarius** [comment]
I cannot provide you with the same syntax as the other repo because this is repo different and currently have no time to rewrite the complete router in a lightwise version.
You are welcome to use the partial groups etc. to create CRUD routes or submit a pull request.
If you have specific wishes, please explain your concept more detailed and I can write your feature request down.

~ Marius

**Comment by aolko** [comment]
> I cannot provide you with the same syntax as the other repo because this is repo different and currently have no time to rewrite the complete router in a lightwise version. You are welcome to use the partial groups etc. to create CRUD routes or submit a pull request. If you have specific wishes, please explain your concept more detailed and I can write your feature request down.
> 
> ~ Marius

just please make a different branch for a rewrite asap

**Comment by DeveloperMarius** [comment]
I can write you wish down for the next year. Can you please describe why I should write a lightwise version and what it should contain? Please write multiple sentences so I can get more detailed insights.

~ Marius

**Comment by RealSocius** [comment]
@aolko is this what you wished for?

**Comment by aolko** [comment]
> @aolko is this what you wished for?

Think so, at least that covers klein.php's syntax partially

**Comment by RealSocius** [comment]
Ok what could I improve to make it better?

**Comment by aolko** [comment]
> Ok what could I improve to make it better?

read [this](https://github.com/klein/klein.php/blob/master/README.md)

**Comment by DeveloperMarius** [comment]
Hello,
because you are not willing to describe your wishes clearly and more detailed, I will close this issue. It is not enough to provide a link to another repo and say "read this".
We have close to all functionality as klein.php but like I already said: This router is different. I cannot adjust the whole syntax.

~ Marius
