### ISSUE TITLE
Php Error on links with multiple following '/'

### ISSUE THREAD

**Issue by Scantech-Val** [DeveloperMarius/simple-php-router#8]
Hi there!

I encounter a PHP error when a link contains more than 2 following '/' in the url (example : http://127.0.0.1:8080///test ):

> PHP ERROR. Typed property Pecee\SimpleRouter\Router::$request must not be accessed before initialization.
> Fatal error on line 844 in file D:\dev\drx\lib\vendor\developermarius\simple-router\src\Pecee\SimpleRouter\Router.php, PHP 8.1.4 (WINNT). Aborting...

There seems to be this bug in both your fork and the original repo.

Could you fix it please? :)
Thanks for your good work for supporting PHP>=8 !

**Comment by DeveloperMarius** [comment]
Hello,

thank you for submitting this issue, I will take a look at it later today. Can you provide me with the route structure (groups and route that (should) match your request), so that I can reproduce the issue better?

~ Marius

**Comment by Scantech-Val** [comment]
The thing is, it happens on existing and non existing routes.
For context, there seems to be hostile people trying to access my website by calling random url like `https://mysite.com///system///sling///loginstatus`.

By trying things, I remarked that the bug only occurs if the 3 `/` are directly following the host name (`https://mysite.com///system///sling///loginstatus` sends an error but `https://mysite.com/system///sling///loginstatus` works fine).

A part of my route structure is like so:
```
Router::group(['namespace'=>'\Drx\Controllers', 'exceptionHandler' => \Drx\Handlers\ExceptionHandler::class], function (){
    // backoffice routes
    Router::group(['prefix'=> '/backoffice', 'middleware' => AuthVerification::class], function(){
        Router::get('/', 'BackOfficeController@index')->setName('backoffice.index');
        Router::get('/logout', 'AppController@logout')->setName('backoffice.logout');
        Router::get('/login', 'BackOfficeController@login')->setName('backoffice.login');
        Router::post('/login', 'AppController@loginAction')->setName('backoffice.loginAction');
        
		// ...
    });
});
```

For info: I tried removing my middleware `AuthVerification` but it doesn't seems to be the cause of the issue.
Just doing `http://127.0.0.1:8080///backoffice/login` should give you an error.

**Comment by Scantech-Val** [comment]
my Exception handlers looks like so:
```
<?php
namespace Drx\Handlers;

use Exception;
use Pecee\Http\Request;
use Pecee\SimpleRouter\Exceptions\NotFoundHttpException;
use Pecee\SimpleRouter\Handlers\IExceptionHandler;

class ExceptionHandler implements IExceptionHandler
{

    /**
     * @param Request $request
     * @param Exception $ex
     * @throws Exception
     */
    public function handleError(Request $request, Exception $ex): void
    {
        if(!($ex instanceof NotFoundHttpException)) manual_error_log($ex->getCode(), $ex->getMessage(), $ex->getFile(), $ex->getLine());
        /* You can use the exception handler to format errors depending on the request and type. */
        if ($request->isAjax()) {
            json([
                'msg' => $ex->getMessage(),
                'success'=>false,
            ]);
        }

        /* The router will throw the NotFoundHttpException on 404 */
        if($ex instanceof NotFoundHttpException) {
            try{
                $msg = 'Page not found:'.$request->getUrl();
                write_db_log(3, array('type'=>'not_found', 'event'=>$msg));
            }catch (Exception | \Error $e){

            }finally {
                if(!empty($_SESSION['UUID'])){
                    $request->setRewriteCallback('Drx\Controllers\MainController@notFound');
                } else {
                    $request->setRewriteCallback('Drx\Controllers\MainController@index');
                }
            }
            return;
        }

        throw $ex;
    }
}
```

**Comment by DeveloperMarius** [comment]
Hello,

thank you, now I can have a better look and will write you soon.

~ Marius

**Comment by DeveloperMarius** [comment]
Hey,

I found the issue. php thinks the `//` is part of the scheme/host part of the url. I fixed this behavior.
Thank you.
Please read the release notes because I found a kind of interesting & dangerous behavior with the multiple slashes.

~ Marius

**Comment by Scantech-Val** [comment]
Thanks, it works as expected now!
